"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[line_break]
disabled = true

[directory]
truncation_length=5
truncation_symbol="/"

[package]
disabled = true

[python]
format = "[($virtualenv )]($style)"

[lua]
disabled = true
